// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dvd_rental.Data;

#nullable disable

namespace dvd_rental.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("dvd_rental.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("dvd_rental.Models.Dvd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataUscita")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurataMinuti")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantitaTotale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dvds");
                });

            modelBuilder.Entity("dvd_rental.Models.Noleggio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataNoleggio")
                        .HasColumnType("TEXT");

                    b.Property<int>("DvdId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("RestituzioneEffettiva")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RestituzionePrevista")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DvdId");

                    b.ToTable("Noleggi");
                });

            modelBuilder.Entity("dvd_rental.Models.Noleggio", b =>
                {
                    b.HasOne("dvd_rental.Models.Cliente", "Cliente")
                        .WithMany("Noleggi")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dvd_rental.Models.Dvd", "Dvd")
                        .WithMany("Noleggi")
                        .HasForeignKey("DvdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Dvd");
                });

            modelBuilder.Entity("dvd_rental.Models.Cliente", b =>
                {
                    b.Navigation("Noleggi");
                });

            modelBuilder.Entity("dvd_rental.Models.Dvd", b =>
                {
                    b.Navigation("Noleggi");
                });
#pragma warning restore 612, 618
        }
    }
}
